version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "feat/dependabot"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      nuget-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/src/front/InSeconds.Client"
    target-branch: "feat/dependabot"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    groups:
      npm-all:
        patterns:
          - "*"
