// <auto-generated />
using System;
using InSeconds.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InSeconds.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InSecondsDbContext))]
    [Migration("20261008071708_DailyDayStats")]
    partial class DailyDayStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("challenges_hilo", "daily")
                .IncrementsBy(10);

            modelBuilder.HasSequence("device_sessions_hilo", "players")
                .IncrementsBy(10);

            modelBuilder.HasSequence("sessions_hilo", "daily")
                .IncrementsBy(10);

            modelBuilder.HasSequence("tracks_hilo", "catalogue")
                .IncrementsBy(10);

            modelBuilder.Entity("InSeconds.Api.Infrastructure.Settings.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", "infra");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Catalogue.Domain.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "tracks_hilo", "catalogue");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("CoverHash")
                        .HasColumnType("text")
                        .HasColumnName("cover_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeezerRank")
                        .HasColumnType("integer")
                        .HasColumnName("deezer_rank");

                    b.Property<long>("DeezerTrackId")
                        .HasColumnType("bigint")
                        .HasColumnName("deezer_track_id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTimeOffset?>("PreviewCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preview_checked_at");

                    b.Property<short>("PreviewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("preview_status");

                    b.Property<DateTimeOffset?>("RankUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rank_updated_at");

                    b.Property<short?>("ReleaseYear")
                        .HasColumnType("smallint")
                        .HasColumnName("release_year");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("DeezerTrackId")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_deezer_track_id");

                    b.ToTable("tracks", "catalogue", t =>
                        {
                            t.HasCheckConstraint("ck_tracks_preview_status", "preview_status IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.ChallengeTrack", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer")
                        .HasColumnName("track_id");

                    b.HasKey("ChallengeId", "Position")
                        .HasName("pk_challenge_tracks");

                    b.HasIndex("TrackId")
                        .HasDatabaseName("ix_challenge_tracks_track_id");

                    b.HasIndex("ChallengeId", "TrackId")
                        .IsUnique()
                        .HasDatabaseName("ix_challenge_tracks_challenge_id_track_id");

                    b.ToTable("challenge_tracks", "daily");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "challenges_hilo", "daily");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<short?>("Origin")
                        .HasColumnType("smallint")
                        .HasColumnName("origin");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.HasKey("Id")
                        .HasName("pk_challenges");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ix_challenges_date");

                    b.ToTable("challenges", "daily");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "sessions_hilo", "daily");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<short>("CurrentHintLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("current_hint_level");

                    b.Property<decimal?>("CurrentListenedSeconds")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("current_listened_seconds");

                    b.Property<short?>("CurrentPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("current_position");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("FreezeEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("freeze_earned");

                    b.Property<short>("FreezesUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("freezes_used");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalListenedSeconds")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("total_listened_seconds");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ChallengeId", "Status")
                        .HasDatabaseName("ix_sessions_challenge_id_status");

                    b.HasIndex("PlayerId", "ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_player_challenge");

                    b.ToTable("sessions", "daily", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_status", "status IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailyStreak", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<short>("Freezes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("freezes");

                    b.Property<DateOnly?>("LastPlayedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_played_date");

                    b.HasKey("PlayerId")
                        .HasName("pk_streaks");

                    b.ToTable("streaks", "daily");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DayStatsSnapshot", b =>
                {
                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Version")
                        .HasColumnType("smallint")
                        .HasColumnName("version");

                    b.HasKey("ChallengeId")
                        .HasName("pk_challenge_day_stats");

                    b.ToTable("challenge_day_stats", "daily");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.SessionAnswer", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("ArtistAnswer")
                        .HasColumnType("text")
                        .HasColumnName("artist_answer");

                    b.Property<bool>("ArtistCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("artist_correct");

                    b.Property<short>("HintLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("hint_level");

                    b.Property<decimal>("ListenedSeconds")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("listened_seconds");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("TitleAnswer")
                        .HasColumnType("text")
                        .HasColumnName("title_answer");

                    b.Property<bool>("TitleCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("title_correct");

                    b.Property<bool>("WasExtended")
                        .HasColumnType("boolean")
                        .HasColumnName("was_extended");

                    b.HasKey("SessionId", "Position")
                        .HasName("pk_answers");

                    b.ToTable("answers", "daily");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.Account", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("pseudo");

                    b.HasKey("PlayerId")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.HasIndex("Pseudo")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_pseudo");

                    b.ToTable("accounts", "players");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("NewEmail")
                        .HasColumnType("citext")
                        .HasColumnName("new_email");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_tokens");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_auth_tokens_player_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_tokens_token_hash");

                    b.ToTable("auth_tokens", "players", t =>
                        {
                            t.HasCheckConstraint("ck_auth_tokens_purpose", "(purpose = 1 AND email IS NOT NULL AND new_email IS NULL) OR (purpose = 2 AND player_id IS NOT NULL AND new_email IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.DeviceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "device_sessions_hilo", "players");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgentLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_agent_label");

                    b.HasKey("Id")
                        .HasName("pk_device_sessions");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_device_sessions_player_id");

                    b.ToTable("device_sessions", "players");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.LegacyToken", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("PlayerId")
                        .HasName("pk_legacy_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_legacy_tokens_token_hash");

                    b.ToTable("legacy_tokens", "players");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", "players");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "infra");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.ChallengeTrack", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Daily.Domain.DailyChallenge", null)
                        .WithMany("Tracks")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_tracks_challenges_challenge_id");

                    b.HasOne("InSeconds.Api.Modules.Catalogue.Domain.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_tracks_tracks_track_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailySession", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Daily.Domain.DailyChallenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_challenges_challenge_id");

                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_players_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailyStreak", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_streaks_players_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DayStatsSnapshot", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Daily.Domain.DailyChallenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_day_stats_challenges_challenge_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.SessionAnswer", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Daily.Domain.DailySession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_sessions_session_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.Account", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithOne()
                        .HasForeignKey("InSeconds.Api.Modules.Players.Domain.Account", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_player_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.AuthToken", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("fk_auth_tokens_player_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.DeviceSession", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_sessions_player_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Players.Domain.LegacyToken", b =>
                {
                    b.HasOne("InSeconds.Api.Modules.Players.Domain.Player", null)
                        .WithOne()
                        .HasForeignKey("InSeconds.Api.Modules.Players.Domain.LegacyToken", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legacy_tokens_player_player_id");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailyChallenge", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("InSeconds.Api.Modules.Daily.Domain.DailySession", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
