// <auto-generated />
using System;
using InSeconds.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InSeconds.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529162622_AddDurationScoresSetting")]
    partial class AddDurationScoresSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InSeconds.Api.Domain.DailyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyChallenges", (string)null);
                });

            modelBuilder.Entity("InSeconds.Api.Domain.DailyChallengeTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("DeezerRankSnapshot")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("DailyChallengeId", "Position")
                        .IsUnique();

                    b.HasIndex("DailyChallengeId", "TrackId")
                        .IsUnique();

                    b.ToTable("DailyChallengeTracks", (string)null);
                });

            modelBuilder.Entity("InSeconds.Api.Domain.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DailyChallengeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "DailyChallengeId")
                        .IsUnique();

                    b.HasIndex("DailyChallengeId", "TotalScore", "TotalDurationSeconds")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_GameSessions_Leaderboard");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DailyChallengeId", "TotalScore", "TotalDurationSeconds"), new[] { "PlayerId" });

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("InSeconds.Api.Domain.GameSessionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistAnswer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ArtistCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("DailyChallengeTrackId")
                        .HasColumnType("int");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("ListenedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("TitleAnswer")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TitleCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("WasExtended")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DailyChallengeTrackId");

                    b.HasIndex("GameSessionId", "DailyChallengeTrackId")
                        .IsUnique();

                    b.ToTable("GameSessionAnswers", (string)null);
                });

            modelBuilder.Entity("InSeconds.Api.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pseudo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuthToken")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Pseudo")
                        .IsUnique()
                        .HasFilter("[IsGuest] = 0 AND [Pseudo] IS NOT NULL");

                    b.ToTable("Players", null, t =>
                        {
                            t.HasCheckConstraint("CK_Players_GuestPseudo", "([IsGuest] = 1 AND [Pseudo] IS NULL) OR ([IsGuest] = 0 AND [Pseudo] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Domain.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Temps de saisie autorisé après la fin de la lecture (en secondes).",
                            Key = "GuessTimerSeconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Durées d'écoute proposées au joueur (CSV, en secondes).",
                            Key = "AllowedDurationsSeconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1,2,3,5,10,15,30"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nombre maximal de prolongations autorisées par réponse.",
                            Key = "MaxExtensionsPerAnswer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nombre de morceaux dans un défi quotidien.",
                            Key = "TracksPerChallenge",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Score de base par palier d'écoute (format palier:score, séparés par virgule).",
                            Key = "DurationScores",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1:1000,2:850,3:700,5:500,10:300,15:150,30:50"
                        });
                });

            modelBuilder.Entity("InSeconds.Api.Domain.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("DeezerTrackId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeezerTrackId")
                        .IsUnique();

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("InSeconds.Api.Domain.DailyChallengeTrack", b =>
                {
                    b.HasOne("InSeconds.Api.Domain.DailyChallenge", "DailyChallenge")
                        .WithMany("Tracks")
                        .HasForeignKey("DailyChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InSeconds.Api.Domain.Track", "Track")
                        .WithMany("DailyChallengeTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyChallenge");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.GameSession", b =>
                {
                    b.HasOne("InSeconds.Api.Domain.DailyChallenge", "DailyChallenge")
                        .WithMany("GameSessions")
                        .HasForeignKey("DailyChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InSeconds.Api.Domain.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyChallenge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.GameSessionAnswer", b =>
                {
                    b.HasOne("InSeconds.Api.Domain.DailyChallengeTrack", "Track")
                        .WithMany("Answers")
                        .HasForeignKey("DailyChallengeTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InSeconds.Api.Domain.GameSession", "GameSession")
                        .WithMany("Answers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.DailyChallenge", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.DailyChallengeTrack", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.GameSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.Player", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("InSeconds.Api.Domain.Track", b =>
                {
                    b.Navigation("DailyChallengeTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
